# Generated by Django 5.2.5 on 2025-09-02 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('content', models.TextField()),
                ('url', models.URLField(max_length=500)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('published_at', models.DateTimeField()),
                ('category', models.CharField(choices=[('geral', 'Geral'), ('esportes', 'Esportes'), ('tecnologia', 'Tecnologia'), ('negócios', 'Negócios')], default='geral', max_length=20)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-published_at'],
                'indexes': [models.Index(fields=['category'], name='api_news_categor_32c3a1_idx'), models.Index(fields=['published_at'], name='api_news_publish_ef6b20_idx')],
            },
        ),
    ]
